@hostname = http://localhost:3000/api/airtable

### Create one event
post {{hostname}}/createEvent
Content-Type: application/json

{
  "name": "Third event",
  "start": "2022-04-16T11:55:00.000Z",
  "end": "2022-04-18T11:55:00.000Z"
}

### Get all events
get {{hostname}}/getEvents

### Update one event
put {{hostname}}/updateEvent
Content-Type: application/json

{
  "id": "recixxjp9Jp5ucCxC",
  "fields": {
    "name": "New event",
    "start": "2022-04-17T11:55:00.000Z",
    "end": "2022-04-19T11:55:00.000Z"
  }
}

### Delete one event
@deleteid = "recF747QsaGzesebQ"
delete {{hostname}}/deleteEvent?id={{deleteid}}

